---
apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
spec:
  selector:
    app: train-schedule
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 3
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: 457335132494.dkr.ecr.us-east-1.amazonaws.com/train-schedule:latest
        image: image: testjenkins.azurecr.io/train-schedule:latest
     #   image: gcr.io/teak-environs-348513/train-schedule:latest
        ports:
        - containerPort: 8080
